import torch
from torch import tensor
from free_range_zoo.envs.wildfire.env.structures.configuration import (
    WildfireConfiguration,
    FireConfiguration,
    AgentConfiguration,
    StochasticConfiguration,
    RewardConfiguration,
)

WildfireConfiguration(
    grid_width=3,
    grid_height=3,
    fire_config=FireConfiguration(
        fire_types=tensor([[0, 2, 1], [2, 0, 2], [1, 2, 0]], dtype=torch.int32),
        num_fire_states=5,
        lit=tensor([[False, True, False], [False, False, False], [False, True, False]]),
        intensity_increase_probability=0.9,
        intensity_decrease_probability=0.85,
        extra_power_decrease_bonus=0.15,
        burnout_probability=0.5,
        base_spread_rate=0.5,
        max_spread_rate=0.0,
        random_ignition_probability=0.25,
        cell_size=200.0,
        wind_direction=0.0,
        ignition_temp=tensor([[2, 2, 2], [2, 2, 2], [2, 2, 2]], dtype=torch.int32),
        initial_fuel=2,
    ),
    agent_config=AgentConfiguration(
        agents=tensor([[0, 0], [1, 1], [2, 2]], dtype=torch.int32),
        fire_reduction_power=tensor([1, 1, 1], dtype=torch.int32),
        attack_range=tensor([1, 1, 1], dtype=torch.int32),
        suppressant_states=3,
        initial_suppressant=2,
        suppressant_decrease_probability=1.0,
        suppressant_refill_probability=1.0,
        initial_equipment_state=2,
        equipment_states=tensor([[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
        repair_probability=1.0,
        degrade_probability=1.0,
        critical_error_probability=0.0,
        initial_capacity=2,
        tank_switch_probability=1.0,
        possible_capacities=tensor([1.0, 2.0, 3.0]),
        capacity_probabilities=tensor([0.0, 1.0, 0.0]),
    ),
    reward_config=RewardConfiguration(
        fire_rewards=tensor([[0.0, 4.0, 2.0], [4.0, 0.0, 4.0], [2.0, 4.0, 0.0]]),
        bad_attack_penalty=-100.0,
        burnout_penalty=-1.0,
        termination_reward=0.0,
    ),
    stochastic_config=StochasticConfiguration(
        special_burnout_probability=True,
        suppressant_refill=True,
        suppressant_decrease=True,
        tank_switch=False,
        critical_error=False,
        degrade=False,
        repair=False,
        fire_increase=True,
        fire_decrease=True,
        fire_spread=True,
        realistic_fire_spread=False,
        random_fire_ignition=True,
        fire_fuel=False,
    ),
)
